#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 22 07:27:52 2020

@author: athenapartch
"""


f = open('Downward_Dog.jpg','rb')

newfile = open('newfile.jpg','wb')

for line in f:
        newfile.write(line)
        
